variables:
  CI_DEBUG_SERVICES: "true"

before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl gettext
  - pip3 install pyyaml --break-system-packages
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t sc-registry.fredhutch.org/review-app-testing:test .
    - docker push sc-registry.fredhutch.org/review-app-testing:test

test:
  stage: test
  services: 
    - name: sc-registry.fredhutch.org/review-app-testing:test
      alias: review-app-testing
  script:
    - sleep 15 && curl -sI  http://review-app-testing:5050  |head -1|grep -q "200 OK"

 
# can the following two jobs be combined and made DRYer?
deploy:
  stage: deploy
  only:
    refs:
        - main
  variables:  # is this necessary?
    IMG_TAG: "latest"
    # are these necessary?
  #   DASH: ""
  #   DOT: ""
  #   SLUG: ""
  script:
    - docker tag sc-registry.fredhutch.org/review-app-testing:test sc-registry.fredhutch.org/review-app-testing:latest
    - docker push sc-registry.fredhutch.org/review-app-testing:latest
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - envsubst < docker-compose.yml > docker-compose-final.yml
    - python3 build_helper.py docker-compose-final.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - review-app-testing

deploy_review_site:
  stage: deploy
  only:
    - branches
  except:
    - main
  variables:
    DASH: "-"
    DOT: "."
    SLUG: $CI_COMMIT_REF_SLUG
  script:
    - echo SLUG is $SLUG
    - docker tag sc-registry.fredhutch.org/review-app-testing:test sc-registry.fredhutch.org/review-app-testing:$CI_COMMIT_REF_SLUG
    - docker push sc-registry.fredhutch.org/review-app-testing:$CI_COMMIT_REF_SLUG
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - envsubst < docker-compose.yml > docker-compose-final.yml
    - python3 build_helper.py docker-compose-final.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - review-app-testing-${SLUG}
