version: '3.3'
services:
  review-app-testing:
    image: sc-registry.fredhutch.org/review-app-testing:${IMG_TAG}
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SLUG}${DASH}review-app-testing.rule=Host(`${HOST}`) && PathPrefix(`/review-app-testing-${SLUG}`)"
        - "traefik.http.routers.${SLUG}${DASH}review-app-testing-secured.rule=Host(`${HOST}`) && PathPrefix(`/review-app-testing-${SLUG}`)"
        - "traefik.http.routers.${SLUG}${DASH}review-app-testing.entrypoints=web,web-secured"
        - #xxxUNCOMMENTTHIStraefik.http.routers.${SLUG}${DASH}review-app-testing.rule=PathPrefix(`/review-app-testing-${SLUG}`)
        - "traefik.http.services.${SLUG}${DASH}review-app-testing.loadbalancer.server.port=5050" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.${SLUG}${DASH}review-app-testing.tls=true"

networks:
  proxy:
    external: true